#!/usr/bin/env sh

#
#
#     .d88888b.
#    d88P" "Y88b
#    888     888
#    888     888
#    888     888
#    888 Y8b 888
#    Y88b.Y8b88P
#     \"Y888888\" point
#           Y8b
#
#
# This is an demo script for Qpoint (https://qpoint.io). Please run:
#
#     curl -s https://get.qpoint.io/install | sudo sh
#
#

set -eu

# configurable variables
VERSION=0.9.3

# script variables
OS=
ARCH=

RED=
GREEN=
PURPLE=
BOLD=
DIM=
RESET=
RESET_BOLD=
# terminal output - use colors
if [ -t 1 ]; then
    RED='[0;31m'
    GREEN='[0;32m'
    PURPLE='[0;35m'
    BOLD='[1m'
    DIM='[2m'
    RESET_BOLD='[22m'
    RESET='[0m'
fi

bold() {
    printf "${BOLD}%s${RESET_BOLD}" "$*"
}

action() {
    printf "${PURPLE}→ %s${RESET}\n" "$*"
}

error() {
    printf >&2 "${RED}✗ %s${RESET}\n" "$*"
    exit 1
}

success() {
    printf "${GREEN}✓ %s${RESET}\n" "$*"
}

download_url() {
    printf "https://downloads.qpoint.io/qpoint/qtap-v%s-%s-%s.tgz" "$VERSION" "$OS" "$ARCH"
}

setup() {
    case "$(uname -sr)" in
    Linux*Microsoft*)
        error "windows/wsl is not supported"
        ;;

    Linux*)
        OS="linux"
        ;;

    *)
        error "unsupported operating system $(bold "$(uname -sr)")"
        ;;
    esac

    case "$(uname -m)" in
    x86_64)
        ARCH="amd64"
        ;;

    aarch64 | arm64)
        ARCH="arm64"
        ;;

    *)
        error "unsupported architecture $(bold "$(uname -m)")"
        ;;
    esac

    if [ "$(id -u)" != "0" ]; then
        error "please run this script as root

    curl -s https://get.qpoint.io/install | sudo sh"
    fi
}

banner() {
    echo ""
    echo "${PURPLE} .d88888b.  ${RESET}"
    echo "${PURPLE}d88P" "Y88b ${RESET}"
    echo "${PURPLE}888     888 ${RESET}"
    echo "${PURPLE}888     888 ${RESET}"
    echo "${PURPLE}888     888 ${RESET}"
    echo "${PURPLE}888 Y8b 888 ${RESET}"
    echo "${PURPLE}Y88b.Y8b88P ${RESET}"
    echo "${PURPLE} \"Y888888\"  ${BOLD}point${RESET}"
    echo "${PURPLE}       Y8b  ${RESET}"
    echo ""
}

install() {
    action "downloading Qtap $(bold "v${VERSION}")"

    if ! dir=$(mktemp -d); then
        error "failed to create temporary directory"
    fi

    cd "$dir"
    # shellcheck disable=SC2064 # we want $dir to expand now
    trap "rm -rf '$dir'" EXIT

    curl -fsSL "$(download_url)" >qtap.tgz
    tar -xzf qtap.tgz
    mv qtap-* qtap
    chmod +x qtap

    success "successfully extracted qtap to $(bold "$(pwd)/qtap")"
    printf '\n'
}

run() {
    action "running Qtap demo"
    echo ""
    ./qtap
}

banner
setup
install
run
