#!/usr/bin/env sh

#
#
#            ••••••••••
#       ••••••••••••••••••••
#     ••••••••••••••••••••••••
#   ••••••••••••••••••••••••••••
#  ••••••••••••••••••••••••••••••
# ••••••••••••••••••••••••••••••••
# ••••••••••••••••••••••••••••••••
#  ••••••••••••••••   •••••••••••
#   •••••••••••••••••   ••••••••
#     •••••••••••••••••   ••••
#       ••••••••••••••••••••
#            ••••••••••      *
#
#          ┏┓ ┏┓ ┏┓ ┳ ┳┓┏┳┓
#          ┃┃ ┃┃ ┃┃ ┃ ┃┃ ┃
#          ┗┣ ┣┛ ┗┛ ┻ ┛┗ ┻
#
# This is a demo script for Qcontrol (https://qpoint.io). Please run:
#
#     curl -s https://get.qpoint.io/qcontrol/demo | sudo sh
#
#

set -eu

# configurable variables
VERSION=${VERSION:-latest}

# script variables
OS=
ARCH=

RED=
GREEN=
PURPLE=
BOLD=
DIM=
RESET=
RESET_BOLD=
# terminal output - use colors
if [ -t 1 ]; then
    RED='[0;31m'
    GREEN='[0;32m'
    PURPLE='[0;35m'
    BOLD='[1m'
    DIM='[2m'
    RESET_BOLD='[22m'
    RESET='[0m'
fi

bold() {
    printf "${BOLD}%s${RESET_BOLD}" "$*"
}

action() {
    printf "${PURPLE}→ %s${RESET}\n" "$*"
}

error() {
    printf >&2 "${RED}✗ %s${RESET}\n" "$*"
}

fatal() {
    error "$*"
    exit 1
}

success() {
    printf "${GREEN}✓ %s${RESET}\n" "$*"
}

download_url() {
    printf "https://downloads.qpoint.io/qcontrol/qcontrol-%s-%s-%s.tgz" "$VERSION" "$OS" "$ARCH"
}

setup() {
    case "$(uname -sr)" in
    Linux*)
        OS="linux"
        ;;

    Darwin*)
        OS="macos"
        ;;

    MINGW* | MSYS* | CYGWIN*)
        OS="win"
        ;;

    *)
        fatal "unsupported operating system $(bold "$(uname -sr)")"
        ;;
    esac

    case "$(uname -m)" in
    x86_64)
        ARCH="amd64"
        ;;

    aarch64 | arm64)
        ARCH="arm64"
        ;;

    *)
        fatal "unsupported architecture $(bold "$(uname -m)")"
        ;;
    esac
}

banner() {
    echo ""
    echo "${PURPLE}           ••••••••••            ${RESET}"
    echo "${PURPLE}      ••••••••••••••••••••       ${RESET}"
    echo "${PURPLE}    ••••••••••••••••••••••••     ${RESET}"
    echo "${PURPLE}  ••••••••••••••••••••••••••••   ${RESET}"
    echo "${PURPLE} ••••••••••••••••••••••••••••••  ${RESET}"
    echo "${PURPLE}•••••••••••••••••••••••••••••••• ${RESET}"
    echo "${PURPLE}•••••••••••••••••••••••••••••••• ${RESET}"
    echo "${PURPLE} ••••••••••••••••   •••••••••••  ${RESET}"
    echo "${PURPLE}  •••••••••••••••••   ••••••••   ${RESET}"
    echo "${PURPLE}    •••••••••••••••••   ••••     ${RESET}"
    echo "${PURPLE}      ••••••••••••••••••••       ${RESET}"
    echo "${PURPLE}           ••••••••••      ${BOLD}*${RESET}"
    echo ""
    echo "${PURPLE}        ┏┓ ┏┓ ┏┓ ┳ ┳┓┏┳┓         ${RESET}"
    echo "${PURPLE}        ┃┃ ┃┃ ┃┃ ┃ ┃┃ ┃          ${RESET}"
    echo "${PURPLE}        ┗┣ ┣┛ ┗┛ ┻ ┛┗ ┻          ${RESET}"
    echo ""
}

install() {
    BINARY="./qcontrol"

    action "downloading Qcontrol [$(bold "${VERSION}")]"

    if ! dir=$(mktemp -d); then
        fatal "failed to create temporary directory"
    fi

    # shellcheck disable=SC2064 # we want $dir to expand now
    trap "rm -rf '$dir'" EXIT INT

    curl -fsSL "$(download_url)" >"${dir}/qcontrol.tgz"
    tar -xzf "${dir}/qcontrol.tgz" -C "$dir"

    if [ -f "$BINARY" ]; then
        error "./qcontrol exists, extracting to /tmp instead"
        BINARY="/tmp/qcontrol-${VERSION}"
    fi
    mv "${dir}"/qcontrol "$BINARY"
    chmod +x "$BINARY"

    success "$(bold "$("$BINARY" --version)") ready to use at $(bold "${BINARY}")"
    printf '\n'
}

run() {
    echo "           ---------"
    echo ""
    "$BINARY" "$@"
}

banner
setup
install

run "--help"
